<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes, HasFactory;


    protected $dates = ['deleted_at'];

    protected $fillable = [
        'title',
        'description',
    ];



    public function user()
    {
        return $this->belongsTo(\App\Models\User::class);
    }

    public function delete()
    {


        return parent::delete(); // TODO: Change the autogenerated stub
    }



}
